name: Build and Release (Windows)

on:
  push:
    tags:
      - 'v*'  # z. B. v1.0, v2.3.4

permissions:
  contents: write


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: lukka/get-cmake@v3.27.7

    - name: Remove old build directory if it exists
      run: if (Test-Path build) { Remove-Item -Recurse -Force build }
    
    - name: Create fresh build directory
      run: mkdir build

    - name: Configure project with CMake
      working-directory: build
      run: cmake ..

    - name: Build project
      working-directory: build
      run: cmake --build . --config Release

    - name: Find built executable
      id: find_exe
      shell: pwsh
      run: |
        $exe = Get-ChildItem -Path build/bin/Release -Filter *.exe -Recurse | Select-Object -First 1
        if ($null -eq $exe) { throw "No .exe file found!" }
        echo "EXE path: $($exe.FullName)"
        echo "exe_path=$($exe.FullName)" >> $env:GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.find_exe.outputs.exe_path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}